[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.50.0"
image = "0.24.5"
nalgebra = "0.32.1"
thiserror = "1.0.38"
